# This is a score between 0 and 1 which will determine how similar an answer must be for it to be recognized recognized right.
# for 1, this would require the user to have an exact answer.
# for 0.9, this would require the user to have a mostly identical answer.
# for 0.8, this would require the user to have only a partially correct answer.
Similarity score: 0.85

# This is the default value for the maximum amount of time players will have to answer a question.
Default time per round: 15

# This is the default value for the total amount of rounds in a game.
Default rounds: 10

# This many amount of players will be shown as winners after a trivia game.
Top winner amount: 3

# These are the questions and answers. The two are separated between a ' /$/ '.
Questions and Answers:
  - "Who is the original creator of Minecraft? /$/ notch"
  - "What do you need to turn powder to concrete? /$/ water"
  - "Is this a trick question? /$/ Yes"
  - "A splash potion of what will heal a skeleton? /$/ Harming"
  - "One block in the nether is equal to how many blocks in the overworld? /$/ 8"
  - "Endermen will become passive after touching what? /$/ Water"
  - "Is it possible to grow a tree past the height limit? /$/ Yes"
  - "What block can spiders not climb up? /$/ Ice"
  - "How many minutes does it take to break a block of obsidian by hand? /$/ 4"
  - "Do cats take fall damage? /$/ No"
  - "It's easier to catch fish in what weather? /$/ Rain"
  - "Creepers were accidently created when Notch was making what mob? /$/ Pig"
  - "Creepers are afraid of what animal? /$/ Ocelots"
  - "One Minecraft block is how many feet? /$/ 3"
  - "How many days did it take to create the original release of Minecraft? /$/ 6"
  - "How many main biomes are there in Minecraft? /$/ 17"
  - "What block can you wear on your head to prevent Endermen from turning hostile while looking at them? /$/ Pumpkin"
  - "Which is more rare, pumpkins or diamonds? /$/ Pumpkins"

# These are the messages that will be displayed during a trivia game.
# Feel free to modify them to your liking.
# Placeholders:
# %player% - player's display name.
# %points% - the amount of trivia questions a player has solved.
# %question% and %answer% - question and answer respectively.
# %questionNum% - the question number.
Messages:
  Trivia Start: "&eTrivia is commencing. Get ready!"
  Trivia Over: "&eTrivia is over!"
  Winner Line: "&6Winners:"
  Winner List: "&0➤ &3%player%: &b%points%"
  No Winners: "&6There are no winners of this trivia event!"
  Solved Message: "&a%player% has answered the question correctly! The answer was &2%answer%&a."
  Question Time Up: "&cTime is up! Next question..."
  Question Display: "&6(%questionNumber%) &e%question%"
