# This is a score between 0 and 1 which will determine how similar an answer must be for it to be recognized recognized right.
# for 1, this would require the user to have an exact answer.
# for 0.9, this would require the user to have a mostly identical answer.
# for 0.8, this would require the user to have only a partially correct answer.
Similarity score: 0.85

# This is the default value for the maximum amount of time players will have to answer a question.
Default time per round: 15

# This is the default value for the total amount of rounds in a game.
Default rounds: 10

# This many amount of players will be shown as winners after a trivia game.
Top winner amount: 3

# These are the questions and answers. The two are separated between a ' /$/ '.
Questions and Answers:
  - "this is the question /$/ this is the answer."
  - "second question /$/ second answer."
  - "third question /$/ third answer."
  - "fourth question /$/ fourth answer."

# These are the messages that will be displayed during a trivia game.
# Feel free to modify them to your liking.
# Placeholders:
# %player% - player's display name.
# %points% - the amount of trivia questions a player has solved.
# %question% and %answer% - question and answer respectively.
# %questionNum% - the question number.
Messages:
  Trivia Start: "&eTrivia is commencing. Get ready!"
  Trivia Over: "&eTrivia is over!"
  Winner Line: "&6Winners:"
  Winner List: "&0➤ &3%player%: &b%points%"
  No Winners: "&6There are no winners of this trivia event!"
  Solved Message: "&a%player% has answered the question correctly! The answer was &2%answer%&a."
  Question Time Up: "&cTime is up! Next question..."
  Question Display: "&6(%questionNumber%) &e%question%"
