# Similarity Score is a score between 0 and 1 which will determine how similar an answer must be for it to be recognized recognized right. Value of 1 requires exact answer, value of 0.8 requires close answer.
Similarity score: 0.85

# Default time per round is the default value for the maximum amount of time (in seconds) players will have to answer a question.
Default time per round: 15

# Default rounds is the default value for the total number of rounds in a game.
Default rounds: 10

# Time between rounds is for the transition time (in seconds) between the rounds themselves.
Time between rounds: 2

# Top winner amount's value will show these many winners displayed in chat after a trivia game.
Top winner amount: 3

# Scheduled games, if true, will let console automatically host trivia every x minutes.
Scheduled games: false

# Scheduled games interval is the time between the scheduled games (in minutes) if scheduled games are enabled.
Scheduled games interval: 60

# Scheduled games minimum players is the minimum number of players that must be on for scheduled trivia events to be hosted.
Scheduled games minimum players: 6

# Summon fireworks, If true, will summon a random firework at the location of the trivia winners.
Summon fireworks: true

# Answer correct sound will be played after a player answers the question correctly. Enter 'none' to play no sound.
# Use sound values found at https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
Answer correct sound: BLOCK_NOTE_BLOCK_PLING
Answer correct pitch: 1.5

# Time up sound will be played after no one has answered the question correctly in time.
Time up sound: ENTITY_VILLAGER_NO
Time up pitch: 0.9

# Game start sound will be played when the trivia game starts. By default, there is no sound.
Game start sound: none
Game start pitch: 1.0

# Game over sound will be played after the trivia game is over.
Game over sound: ENTITY_PLAYER_LEVELUP
Game over pitch: 0.9

# Question and Answers are where the trivia questions are stored. The two are separated between a ' /$/ '.
Questions and Answers:
  - "Who is the original creator of Minecraft? /$/ notch"
  - "What do you need to turn powder to concrete? /$/ water"
  - "Is this a trick question? /$/ Yes"
  - "A splash potion of what will heal a skeleton? /$/ Harming"
  - "One block in the nether is equal to how many blocks in the overworld? /$/ 8"
  - "Endermen will become passive after touching what? /$/ Water"
  - "Is it possible to grow a tree past the height limit? /$/ Yes"
  - "What block can spiders not climb up? /$/ Ice"
  - "How many minutes does it take to break a block of obsidian by hand? /$/ 4"
  - "Do cats take fall damage? /$/ No"
  - "It's easier to catch fish in what weather? /$/ Rain"
  - "Creepers were accidentally created when Notch was making what mob? /$/ Pig"
  - "Creepers are afraid of what animal? /$/ Ocelots"
  - "One Minecraft block is how many feet? /$/ 3"
  - "How many days did it take to create the original release of Minecraft? /$/ 6"
  - "How many main biomes are there in Minecraft? /$/ 17"
  - "What block can you wear on your head to prevent Endermen from turning hostile while looking at them? /$/ Pumpkin"
  - "Which is more rare, pumpkins or diamonds? /$/ Pumpkins"

# The "messages" section are the messages that will be displayed during a trivia game.
# Feel free to modify them to your liking.
# Placeholders:
# %player% - player's display name.
# %points% - the amount of trivia questions a player has solved.
# %question% and %answer% - question and answer respectively.
# %questionNum% - the question number.
Messages:
  Trivia Start: "&eTrivia is commencing. Get ready!"
  Trivia Over: "&eTrivia is over!"
  Winner Line: "&6Winners:"
  Winner List: "&0➤ &3%player%: &b%points%"
  No Winners: "&6There are no winners of this trivia event!"
  Solved Message: "&a%player% has answered the question correctly! The answer was &2%answer%&a."
  Question Time Up: "&cTime is up! Next question..."
  Question Display: "&6(%questionNumber%) &e%question%"

# This is to keep track of what config version this is. Do not modify!
Config Version: 2