name: Trivia
version: "1.4"
main: me.marcarrots.trivia.Trivia
api-version: 1.13
authors: [MarCarrot]
description: Trivia plugin for Minecraft Spigot
softdepend:
  - Vault
commands:
  trivia:
    description: Trivia command.
    permission: trivia.admin
